### ISSUE TITLE
提取网页文本出错

### ISSUE THREAD

**Issue by offlinenow** [tricomm/neteasenews#5]
试着直接测试了一下`basenews.py`里的`getanews()`函数，报了一个错。    
测试网址`http://ent.163.com/17/0413/21/CHUBHJ7C00038FO9.html`     
报错内容为：
````
Traceback (most recent call last):
  File "neteasenews/basenews.py", line 22, in <module>
    getanews('http://ent.163.com/17/0413/21/CHUBHJ7C00038FO9.html')
  File "neteasenews/basenews.py", line 14, in getanews
    del subject_tag['class']
TypeError: 'NoneType' object does not support item deletion
````
也就是说没匹配到东西，当然什么都删不了。    
先试试匹配`<div class="post_text" id="endText" style="border-top:1px solid #ddd;">`，不行再说

**Comment by offlinenow** [comment]
Update:
`<p class='otitle'>`只是表示新闻的原标题，如果没有原标题就会报错
